In [1]:
import numpy as np

## Brodcasting

In [2]:
import numpy as np

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [11]:
11 = [0,1,2,3,4,5,6,7,8,9]

SyntaxError: cannot assign to literal (<ipython-input-11-9c175e1e341f>, line 1)

In [13]:
l1 = [0,1,2,3,4,5,6,7,8,9]

l1

In [14]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
l1[1]/10

0.1

In [16]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [18]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [19]:
arr[arr>5]

array([6, 7, 8, 9])

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1 = arr[0:6]

In [24]:
arr1

array([0, 1, 2, 3, 4, 5])

In [25]:
arr[:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr1[:] = 555

In [28]:
arr1

array([555, 555, 555, 555, 555, 555])

In [29]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

## Copy of an Array

In [30]:
arr2 = arr.copy()

In [31]:
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [32]:
arr2[:]=1000

In [33]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [34]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

## Python List Vs Numpy Array

In [35]:
size =1000
x = range(size)
y = range(size)        

In [36]:
%%timeit
[x[i]*y[i] for i in range(size)]

212 µs ± 2.21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [37]:
x1 = np.arange(size)
y1 = np.arange(size)

In [38]:
%%timeit
x1*y1

1.23 µs ± 1.91 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Insert

In [40]:
b = np.array([[1,2,3],[4,5,6,],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
b1 = np.insert(b,1,[15,16,17],axis=0)
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [47]:
np.insert(b,1,[15,16,17],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [48]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## Matrix

In [51]:
x = np.matrix('1,2,3;4,5,6;7,8,9,')

In [52]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[2,1]= -7

In [55]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [56]:
arr = np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr[2,1] = -7

In [64]:
np.insert(arr,2,2)

array([ 1,  2,  2,  3,  4,  5,  6,  7, -7,  9])

In [65]:
x*x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [66]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [67]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

## Storage in File

In [68]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [69]:
np.savetxt('a.txt',arr)

In [70]:
np.savetxt('a.txt',arr,delimiter=',')

In [72]:
np.loadtxt('a.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [73]:
np.save('data.npy',arr)

In [74]:
np.load('data.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [75]:
a = np.arange(10)

In [76]:
np.savez('both.npz',arr,a)

In [77]:
z = np.load('both.npz')

In [78]:
z.files

['arr_0', 'arr_1']

In [79]:
z[z.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [80]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## pandas

In [81]:
import pandas as pd
import numpy as np

## Using List

In [89]:
my_list = [100,200,300,400,500]

In [90]:
x = pd.Series(my_list,index = ['A','B','C','D','E'])
x

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [91]:
type(x)

pandas.core.series.Series

## Using Numpy Array

In [92]:
arr = np.array(my_list)
arr

array([100, 200, 300, 400, 500])

In [95]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [99]:
pd.Series(arr,'A B C D E'.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

## Using Dictionary

using dictionaries

In [103]:
dict1 = {'A':100,'B':200,'C':300}
dict1

{'A': 100, 'B': 200, 'C': 300}

In [105]:
z1=pd.Series(dict1)
z1

A    100
B    200
C    300
dtype: int64

In [110]:
z2 =pd.Series([10,20,30,40],'A B C D'.split())
z2

A    10
B    20
C    30
D    40
dtype: int64

In [111]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

## Slicing in Series

In [112]:
z2[0:2]

A    10
B    20
dtype: int64

In [113]:
z2['A':'B']

A    10
B    20
dtype: int64

## .loc and .iloc

In [114]:
z2.loc['A':'B']

A    10
B    20
dtype: int64

In [118]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [120]:
z=pd.Series({100:'a',200:'b',300:'c'})
z

100    a
200    b
300    c
dtype: object

In [121]:
z[0]

KeyError: 0

In [122]:
z.iloc[0]

'a'

## Operation

In [123]:
z1

A    100
B    200
C    300
dtype: int64

In [127]:
z1>100

A    False
B     True
C     True
dtype: bool

In [128]:
z1<200

A     True
B    False
C    False
dtype: bool

## Broadcasting

In [129]:
z1+300


A    400
B    500
C    600
dtype: int64

## Ordering

In [130]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [131]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [132]:
z2.min()

10

In [133]:
z2.max()

40

In [136]:
z2.idxmax()

'D'

# DataFrame

In [137]:
rand_mat = np.random.randn(5,4)

In [138]:
rand_mat

array([[ 0.14272296,  1.22077858, -0.41750143, -0.88536342],
       [ 0.00603866,  0.64409042, -0.1877161 , -0.58006808],
       [-0.90913138, -0.74132889,  1.54919217,  0.19613548],
       [-0.42476767, -0.41663586,  2.45106807,  1.38640557],
       [ 0.13093225,  0.06763933, -0.06813325,  0.6812381 ]])

In [139]:
df = pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())

In [140]:
df

W         X         Y         Z
A  0.142723  1.220779 -0.417501 -0.885363
B  0.006039  0.644090 -0.187716 -0.580068
C -0.909131 -0.741329  1.549192  0.196135
D -0.424768 -0.416636  2.451068  1.386406
E  0.130932  0.067639 -0.068133  0.681238

In [142]:
type(df)

pandas.core.frame.DataFrame

In [143]:
df['W']

A    0.142723
B    0.006039
C   -0.909131
D   -0.424768
E    0.130932
Name: W, dtype: float64

In [144]:
type(df['W'])

pandas.core.series.Series

## Selection and Indexing

In [145]:
df.loc['A']

W    0.142723
X    1.220779
Y   -0.417501
Z   -0.885363
Name: A, dtype: float64

In [146]:
df[['W','Z']]

W         Z
A  0.142723 -0.885363
B  0.006039 -0.580068
C -0.909131  0.196135
D -0.424768  1.386406
E  0.130932  0.681238

## Add a New Column

In [147]:
df['New'] = df['W'] + df['Z']

In [148]:
df

W         X         Y         Z       New
A  0.142723  1.220779 -0.417501 -0.885363 -0.742640
B  0.006039  0.644090 -0.187716 -0.580068 -0.574029
C -0.909131 -0.741329  1.549192  0.196135 -0.712996
D -0.424768 -0.416636  2.451068  1.386406  0.961638
E  0.130932  0.067639 -0.068133  0.681238  0.812170

In [149]:
df.drop('New',axis=1)

W         X         Y         Z
A  0.142723  1.220779 -0.417501 -0.885363
B  0.006039  0.644090 -0.187716 -0.580068
C -0.909131 -0.741329  1.549192  0.196135
D -0.424768 -0.416636  2.451068  1.386406
E  0.130932  0.067639 -0.068133  0.681238

In [150]:
df

W         X         Y         Z       New
A  0.142723  1.220779 -0.417501 -0.885363 -0.742640
B  0.006039  0.644090 -0.187716 -0.580068 -0.574029
C -0.909131 -0.741329  1.549192  0.196135 -0.712996
D -0.424768 -0.416636  2.451068  1.386406  0.961638
E  0.130932  0.067639 -0.068133  0.681238  0.812170

In [152]:
df.drop('New',axis =1,inplace=True)

In [153]:
df

W         X         Y         Z
A  0.142723  1.220779 -0.417501 -0.885363
B  0.006039  0.644090 -0.187716 -0.580068
C -0.909131 -0.741329  1.549192  0.196135
D -0.424768 -0.416636  2.451068  1.386406
E  0.130932  0.067639 -0.068133  0.681238

## Add a New row

In [154]:
df.loc['F'] = df.loc['A']+df.loc['C']

In [155]:
df

W         X         Y         Z
A  0.142723  1.220779 -0.417501 -0.885363
B  0.006039  0.644090 -0.187716 -0.580068
C -0.909131 -0.741329  1.549192  0.196135
D -0.424768 -0.416636  2.451068  1.386406
E  0.130932  0.067639 -0.068133  0.681238
F -0.766408  0.479450  1.131691 -0.689228

In [156]:
df.drop('F',axis=0,inplace=True)

In [157]:
df

W         X         Y         Z
A  0.142723  1.220779 -0.417501 -0.885363
B  0.006039  0.644090 -0.187716 -0.580068
C -0.909131 -0.741329  1.549192  0.196135
D -0.424768 -0.416636  2.451068  1.386406
E  0.130932  0.067639 -0.068133  0.681238

In [158]:
df['X']['C']

-0.7413288860482181

In [160]:
df.loc['C']['X']

-0.7413288860482181

## Data Input & Output

In [163]:
pd.read_csv('example.csv')

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2021                     Level 1                99999   
1      2021                     Level 1                99999   
2      2021                     Level 1                99999   
3      2021                     Level 1                99999   
4      2021                     Level 1                99999   
...     ...                         ...                  ...   
41710  2013                     Level 3                 ZZ11   
41711  2013                     Level 3                 ZZ11   
41712  2013                     Level 3                 ZZ11   
41713  2013                     Level 3                 ZZ11   
41714  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
41710  Food product manufacturing          Percentage           H37   
41711  Food product manufacturing          Percentage           H38   
41712  Food product manufacturing          Percentage           H39   
41713  Food product manufacturing          Percentage           H40   
41714  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
41710                                      Quick ratio       Financial ratios   
41711              Margin on sales of goods for resale       Financial ratios   
41712                                 Return on equity       Financial ratios   
41713                           Return on total assets       Financial ratios   
41714                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1      674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2       49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3       33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,404  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
41710       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41711       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41712       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41713        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41714       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[41715 rows x 10 columns]

## Statistics function

In [165]:
x= np. array([[1,2,3],[2,4,6],[90,100,50]])

In [166]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [167]:
np.amin(x)

1

In [168]:
np.amax(x)

100

In [169]:
np.amin(x, axis=1)

array([ 1,  2, 50])

In [170]:
np.amin(x, axis=0)

array([1, 2, 3])

In [172]:
np.amax(x, axis=0)

array([ 90, 100,  50])

In [173]:
np.amax(x, axis=1)

array([  3,   6, 100])

In [174]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [175]:
np.average(x)

28.666666666666668

## Weightted average

In [176]:
w=[1,2,3,]

In [177]:
np.average(x, weights= w, axis=0)

array([45.83333333, 51.66666667, 27.5       ])

In [178]:
np.average(x,weight=w,axis =1)

TypeError: _average_dispatcher() got an unexpected keyword argument 'weight'

In [179]:
np.means(x[3])

AttributeError: module 'numpy' has no attribute 'means'

In [180]:
np.average(x, weights=w,axis =1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [181]:
np.mean(x)

28.666666666666668

In [182]:
np.mean(x[0])

2.0

In [183]:
np.mean(x[1])

4.0

In [184]:
np.mean(x[2])
        

80.0

In [185]:
np.mean(x,axis=0)

array([31.        , 35.33333333, 19.66666667])

In [186]:
np.mean(x, axis=1)

array([ 2.,  4., 80.])

In [187]:
np.median(x)

4.0

In [188]:
np.median(x, axis=0)

array([2., 4., 6.])

In [189]:
np.median(x, axis=1)

array([ 2.,  4., 90.])

In [190]:
np.std(x)

38.4042821686448